CREATE DATABASE bolsaVGo;

USE bolsaVGo;

CREATE TABLE tblTickers (
    tic_id INT UNSIGNED AUTO_INCREMENT,
    tic_empresa VARCHAR(255) NOT NULL,
    tic_ticker VARCHAR(10) NOT NULL UNIQUE,
    tic_update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tic_create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tic_id)
);